### ISSUE TITLE
Have you tried large input images (600 * 1000)?

### ISSUE THREAD

**Issue by mqchen1993** [szq0214/DSOD#28]
First of all, the idea of training from scratch is awesome. I have a question. Have you tried large input images (600 * 1000)?

**Comment by szq0214** [comment]
Hi @mqchen1993, thanks very much for your interests!

Large inputs may help to further improve the detection performance, but it's very hard for us to try it because our batch size has already been very large (128). This hyper-parameter affects the performance a lot. If adopting large inputs like 600*1000 or 512*512, the training process will become extremely time and memory-consuming. We don't have sufficient GPUs to finish these experiments.
